MIN_TICK = 60

## NORMAL ##
NORMAL_DELAY_SEC = MIN_TICK

## NORMAL-INTEREST ##
NORMAL_INTEREST_PRICE_PT = 2 # %
WATCH_PRICE_PT_THRESHOLD = 5 # %
MAX_WATCH_TIME = 60 * 10     # min
ADD_COMMENTS_TRESHOLD = 2

## INTEREST ##
INTEREST_WATCH_SEC = 10
INTEREST_TIME_MAX = MIN_TICK # sec

## INTEREST-SENSITIVE ##
INTEREST_SENSITIVE_BUY_THRESHOLD = 30 
INTEREST_SENSITIVE_STRENGTH = 120 # %


